### ISSUE TITLE
NOT MacOS: ModuleNotFoundError: No module named 'AppKit'

### ISSUE THREAD

**Issue by theandrelima** [Townk/ansible-beautiful-output#4]
My environment is:
Windows 10, with WSL 2.0 running Ubuntu 20.04.

Now, inside that Ubuntu OS, I'm running a container with Ansible.  Although this sounds convoluted, this is just a sandbox for the environment in my company. Ultimately, what I want to stress is that I'm not using MacOS. It's ansible on Linux. 

With that said, I made sure to add `watchdog` to the environment and got the plugin:

```
$ ansible-galaxy install townk.beautiful_output
- downloading role 'beautiful_output', owned by townk
- downloading role from https://github.com/Townk/ansible-beautiful-output/archive/v0.7.0.tar.gz
- extracting townk.beautiful_output to <redacted>/shared/roles/townk.beautiful_output
- townk.beautiful_output (v0.7.0) was installed successfully
```

And then I added the role to my playbook:
```
roles:
    - role: townk.beautiful_output
```

When I execute the playbook, I still get the error:
```
ERROR! Unexpected Exception, this is probably a bug: No module named 'AppKit'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/usr/local/lib/python3.7/site-packages/ansible/executor/playbook_executor.py", line 99, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python3.7/site-packages/ansible/executor/task_queue_manager.py", line 134, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
  File "/usr/local/lib/python3.7/site-packages/ansible/plugins/loader.py", line 552, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python3.7/site-packages/ansible/plugins/loader.py", line 525, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/local/shared/roles/townk.beautiful_output/callback_plugins/beautiful_output.py", line 87, in <module>
    from watchdog.observers.fsevents2 import FSEventsObserver2 as Observer
  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/fsevents2.py", line 47, in <module>
    import AppKit
ModuleNotFoundError: No module named 'AppKit'
```

From the docs, I understood AppKit would be required only for MacOS, but not for Linux. 
Also, in that case, the suggestion is to not install AppKit directly, but  a few other packages instead. 
Could you clarify what should I do next to be able to use this role in Linux?

**Comment by theandrelima** [comment]
So this commit fixes the issue: https://github.com/Townk/ansible-beautiful-output/commit/520303a4b697edaeeeb9465b6b1c3dda9d1ff0bb
